spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/rewardsystem
    username: root
    password: NOOR28muzib18*
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8181
